server:
  port: 8083

spring:
  application:
    name: cloud-consumer-feign-hystrix-order-8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

feign:
  hystrix:
    enabled: true #在feign中开启hystrix
